markdown: GFM
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: veOGV
description: veOGV is a governance vote-escrowed token built on Ethereum by the team at Origin Protocol